FILESEXTRAPATHS_append := "${THISDIR}/${PN}/"
SRCREV_meta-bsp ?= "a39914e5ab19acaf1c1f10260a87fefa606d02a7"
SRC_URI += "git://github.com/gmzhuo/yocto-kernel-cache.git;type=kmeta;name=meta-bsp;branch=yocto-5.4;protocol=https;destsuffix=${KMETA}"
COMPATIBLE_MACHINE += "|qcom-ipq807x"
SRC_URI += "file://qcom-ipq807x-dts-nandc.patch file://710-net-add-qualcomm-essedma-ethernet-driver.patch"
SRC_URI += "file://703-net-IPQ4019-needs-rfs-vlan_tag-callbacks-in.patch"
